### ISSUE TITLE
passiogo.printAllSystemsMd() returns only #951

### ISSUE THREAD

**Issue by adelgadorios** [athuler/PassioGo#22]
Whenever I run passiogo.printAllSystemsMd() or system = passiogo.getSystemFromID(1068) I get the following output:

{'fullname': '3630 Peachtree', 'username': 'peachtree', 'goAgencyName': None, 'id': '951', 'email': None, 'goTestMode': '0', 'name2': '0', 'homepage': None, 'logo': 0, 'goRoutePlannerEnabled': '0', 'goColor': None, 'goSupportEmail': None, 'goAuthenticationType': '0'}

**Comment by athuler** [comment]
I've replicated the issue. Working on a fix.

**Comment by athuler** [comment]
This issue should be fixed with `0.2.2`. Please update and let me know if you are still seeing an issue!

**Comment by adelgadorios** [comment]
The issue is fixed, thank you!
